In [13]:
import numpy as np # импорт библиотеки numpy
b = np.array([[1, 2], [4, 5]]) # создаём двумерный массив
b

b.shape # форма массива

с = np.ones((2, 2)) # создание массива из единиц
с

a=np.arange(20, 30, 5)
a

a.dtype # определение типа данных

d=np.arange(30, 40, 5)
d

e=a+d # сложение массивов поэлементно
e

e.min() # минимальный элемент массива

e.max() # максимальный элемент массива

f = np.arange(10) # создание массива из 10 элементов
f

f[2:7] # срез с третьего по седьмой элемента массива

array([2, 3, 4, 5, 6])

In [14]:
с = np.ones((2, 2)) # создание массива из единиц
с

array([[1., 1.],
       [1., 1.]])

In [15]:
b = np.array([[1, 2], [4, 5]]) # создаём двумерный массив
b

array([[1, 2],
       [4, 5]])

In [16]:
b.shape # форма массива

(2, 2)

In [17]:
a=np.arange(20, 30, 5)
a

array([20, 25])

In [18]:
a.dtype # определение типа данных

dtype('int64')

In [19]:
d=np.arange(30, 40, 5)
d

array([30, 35])

In [20]:
e=a+d # сложение массивов поэлементно
e

array([50, 60])

In [21]:
e.min() # минимальный элемент массива

np.int64(50)

In [22]:
e.max() # максимальный элемент массива

np.int64(60)

In [23]:
f = np.arange(10) # создание массива из 10 элементов
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
f[2:7] # срез с третьего по седьмой элемента массива

array([2, 3, 4, 5, 6])